import type { Metadata, Viewport } from "next";
import { Instrument_Serif, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
// The icon font, self-hosted and subset to what this app uses. Imported here
// rather than <link>ed, so Next bundles it (and keeps eslint's no-css-tags
// happy); the @font-face inside points at /fonts/tabler-subset.woff2.
// Generated by scripts/build-icon-font.mjs — see the note in <head> below.
import "@/styles/tabler-subset.css";
import { AuthProvider } from "@/lib/auth-context";
import { ServiceWorkerRegister } from "@/components/pwa/ServiceWorkerRegister";
import { TwaContextProbe } from "@/components/pwa/TwaContextProbe";
import {
  SITE_URL,
  SITE_NAME,
  SITE_TAGLINE,
  SITE_DESCRIPTION,
  DEFAULT_OG_IMAGE,
} from "@/lib/site-config";

/*
 * Loaded through next/font, NOT a <link> to fonts.googleapis.com.
 *
 * next/font self-hosts the files at build time, which keeps the "no
 * external fetch required" property the old system-font stack was chosen
 * for, and avoids adding a second render-blocking stylesheet from a third
 * party — the exact problem the Tabler icon font was self-hosted to fix.
 * It also emits the @font-face with font-display: swap and preloads, so
 * there is no flash of invisible text.
 *
 * Both expose a CSS variable rather than a class, so globals.css can point
 * the existing --font-display / --font-body at them and every component
 * keeps working untouched.
 */

// Display only, and never below 24px — the strokes are thin enough to
// disappear at small sizes. One weight is all it ships.
const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-instrument-serif",
});

// Everything else. Four weights, because the design steps by weight rather
// than by size below 15px.
//
// Chosen partly for two things that are not about this redesign: IBM Plex
// Sans Arabic is the same family, so the Arabic surface later needs no
// type-system change, and Plex has tabular figures, which is what keeps
// price columns aligned.
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-ibm-plex-sans",
});

export const metadata: Metadata = {
  // Lets every page below give openGraph.images and canonical URLs as plain
  // paths — Next resolves them against this. Without it, relative image
  // paths are dropped from the tags entirely and share cards come out blank.
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    // Pages set a bare title; the brand is appended here so there is one
    // place to change it and no page can forget it.
    template: `%s — ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  manifest: "/manifest.json",
  appleWebApp: { capable: true, title: SITE_NAME, statusBarStyle: "default" },
  // Every one of these links gets pasted into WhatsApp during the cold call
  // sprint, and a link with no preview card reads as broken.
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en_US",
    url: SITE_URL,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: [{ url: DEFAULT_OG_IMAGE, width: 512, height: 512, alt: SITE_NAME }],
  },
  // Card type only, deliberately. Next merges metadata per key, not per
  // field: a page that sets openGraph but not twitter keeps the root's
  // twitter block wholesale, so a title here would put "Fann — Book
  // Lebanon's live talent" on the Twitter card of every page on the site.
  // With no title, description or image, consumers fall back to the
  // OpenGraph tags, which every page does set correctly.
  twitter: { card: "summary_large_image" },
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  themeColor: "#3a2317",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${instrumentSerif.variable} ${ibmPlexSans.variable}`}
    >
      <head>
        {/* Self-hosted, and subset to the icons this app actually uses.

            This was a render-blocking stylesheet from cdn.jsdelivr.net on
            every page, which meant a blocked or slow CDN gave a page of
            invisible icons — seen for real during development, not a
            hypothetical. Serving it ourselves removes a third party from
            the critical path of every render.

            Subset rather than the whole font on purpose: the full webfont
            is 753KB of woff2 plus a 197KB stylesheet for ~4900 icons, of
            which this app uses 73. The subset is 14KB + 3KB.

            The stylesheet itself is imported by globals.css; this preload
            just starts the font fetch alongside it instead of after it.

            Generated by scripts/build-icon-font.mjs. ADDING AN ICON MEANS
            RE-RUNNING IT — a name outside the subset renders as nothing,
            silently. `npm run check:icons` (part of verify) fails the build
            if the two drift. */}
        <link rel="preload" as="font" type="font/woff2" href="/fonts/tabler-subset.woff2" crossOrigin="anonymous" />
      </head>
      <body className="min-h-full flex flex-col bg-surface">
        <ServiceWorkerRegister />
        <TwaContextProbe />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
